// Generated by CoffeeScript 1.3.3
"use strict";

angular.module("Courses", ["Courses.filters", "Courses.services", "Courses.directives"]).config([
  "$routeProvider", function($routeProvider) {
    $routeProvider.when("/", {
      templateUrl: "partials/root.html",
      controller: rootCtrl
    });
    return $routeProvider.otherwise({
      redirectTo: "/"
    });
  }
]);
