// Generated by CoffeeScript 1.3.3
"use strict";

angular.module("Courses", ["Courses.filters", "Courses.services", "Courses.directives", "elasticjs.service", 'ui']).config([
  "$routeProvider", function($routeProvider) {
    $routeProvider.when("/schedule", {
      templateUrl: "partials/root.html",
      controller: rootCtrl,
      reloadOnSearch: false
    });
    return $routeProvider.otherwise({
      redirectTo: "/schedule"
    });
  }
]);


if (!Array.prototype.filter) {
  Array.prototype.filter = function(fun /*, thisp*/) {
    var len = this.length >>> 0;
    if (typeof fun != "function")
    throw new TypeError();

    var res = [];
    var thisp = arguments[1];
    for (var i = 0; i < len; i++) {
      if (i in this) {
        var val = this[i]; // in case fun mutates this
        if (fun.call(thisp, val, i, this))
        res.push(val);
      }
    }
    return res;
  };
}
;

