// Generated by CoffeeScript 1.3.3
"use strict";

var rootCtrl;

rootCtrl = function($scope, Course, Calendar) {
  var calendar;
  calendar = new Calendar;
  $scope.hours = Calendar.hours;
  $scope.days = Calendar.days;
  $scope.semesters = Calendar.getValidSemesters();
  $scope.selectedSemester = $scope.semesters[0];
  $scope.searchResults = [];
  $scope.courseCalendar = calendar.courseCalendar;
  $scope.search = function() {
    if (!$scope.searchQuery || $scope.searchQuery.length === 0) {
      $scope.clearResults();
      return;
    }
    return Course.search($scope.searchQuery, $scope.selectedSemester).then(function(data) {
      console.log(data);
      return $scope.searchResults = data;
    });
  };
  $scope.clearResults = function() {
    return $scope.searchResults = [];
  };
  $scope.courseSelect = function(course) {
    $scope.clearResults();
    if (calendar.courses[course.id]) {
      return;
    }
    return course.getSections().then(function(status) {
      if (!status) {
        return;
      }
      return calendar.addCourse(course);
    });
  };
  $scope.removeCourse = function(id) {
    return calendar.removeCourse(id);
  };
  return $scope.sectionSelect = function(subsection) {
    var section;
    section = subsection.parent;
    if (!section.parent.status) {
      return;
    }
    return calendar.sectionChosen(section);
  };
};
