// Generated by CoffeeScript 1.3.3
'use strict';

var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

angular.module('Courses.services', []).factory('Course', function($http, $q) {
  var Course;
  return Course = (function() {

    Course.api_url = 'http://data.adicu.com/courses';

    Course.api_token = '515abdcf27200000029ca515';

    function Course(data) {
      this.data = data;
      this.getInfo = __bind(this.getInfo, this);

      if (!(data.MeetsOn1 != null)) {
        return;
      }
      this.id = data.CallNumber;
      this.title = data.CourseSubtitle;
      this.description = data.Description;
      this.course_key = data.Course;
      this.semester = data.Term;
      this.points = data.NumFixedUnits / 10.0;
      this.sections = [];
      this.sections[0] = {
        parentId: this.id,
        title: this.title,
        days: Course.parseDays(this.data.MeetsOn1),
        points: this.points,
        start: Course.parseTime(this.data.StartTime1),
        end: Course.parseTime(this.data.EndTime1)
      };
    }

    Course.prototype.getInfo = function() {
      var d,
        _this = this;
      d = $q.defer();
      if (this.sections) {
        return d.promise;
      }
      $http({
        method: 'JSONP',
        url: Course.api_url,
        params: {
          course_key: this.course_key,
          term: this.semester,
          jsonp: 'JSON_CALLBACK'
        }
      }).success(function(data, status, headers, config) {
        _this.points = data.points;
        _this.sections = data.sections;
        return d.resolve(_this);
      }).error(function(data, status) {
        return d.reject(status);
      });
      return d.promise;
    };

    Course.search = function(query, semester, length, page) {
      var d;
      d = $q.defer();
      $http({
        method: 'JSONP',
        url: Course.api_url,
        params: {
          description: query,
          term: semester,
          limit: length,
          page: page,
          jsonp: 'JSON_CALLBACK',
          api_token: Course.api_token
        }
      }).success(function(data, status, headers, config) {
        var out, result, _i, _len, _ref;
        if (!data.data) {
          return;
        }
        out = [];
        _ref = data.data;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          result = _ref[_i];
          out.push(new Course(result));
        }
        return d.resolve(out);
      }).error(function(data, status) {
        return d.reject(status);
      });
      return d.promise;
    };

    Course.parseDays = function(days) {
      var day, daysAbbr, daysInt, _i, _len;
      daysAbbr = "MTWRF";
      daysInt = [];
      for (_i = 0, _len = days.length; _i < _len; _i++) {
        day = days[_i];
        if (daysAbbr.indexOf(day !== -1)) {
          daysInt.push(daysAbbr.indexOf(day));
        }
      }
      return daysInt;
    };

    Course.parseTime = function(time) {
      var hour, intTime, minute;
      hour = parseInt(time.slice(0, 2));
      minute = parseInt(time.slice(3, 5));
      return intTime = hour + minute / 60.0;
    };

    return Course;

  }).call(this);
}).factory('Calendar', function(Course) {
  var Calendar;
  return Calendar = (function() {

    function Calendar() {
      this.showAllSections = __bind(this.showAllSections, this);

      var i, _i;
      this.courses = {};
      this.courseCalendar = [];
      for (i = _i = 0; _i <= 6; i = ++_i) {
        this.courseCalendar[i] = [];
      }
    }

    Calendar.prototype.addCourse = function(course) {
      var day, section, sectionNum, _i, _len, _ref, _results;
      if (this.courses[course.id] != null) {
        return;
      }
      this.courses[course.id] = course;
      sectionNum = 0;
      section = course.sections[sectionNum];
      section.computedCss = Calendar.computeCss(section.start, section.end);
      _ref = section.days;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        day = _ref[_i];
        console.log('day: ' + day);
        _results.push(this.courseCalendar[day].push(section));
      }
      return _results;
    };

    Calendar.prototype.showAllSections = function(course) {
      var day, newSection, overlap, overlapCheck, section, _i, _j, _len, _len1, _ref, _ref1, _results;
      course.sectionRefs = [];
      overlapCheck = {};
      _ref = course.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        newSection = {
          'id': section.id,
          'computedCss': Calendar.computeCss(section.start, section.end),
          'title': section.title,
          'points': course.points,
          'days': Course.getDays(section)
        };
        overlap = overlapCheck[section.start + '' + section.end + section.days];
        if (!overlap) {
          course.sectionRefs.push(newSection);
          overlapCheck[section.start + '' + section.end + section.days] = newSection;
        } else {
          if (!overlap.overlaps) {
            overlap.overlaps = [];
          }
          overlap.overlaps.push(newSection);
        }
      }
      console.log(course.sectionRefs);
      console.log(overlapCheck);
      this.courses.push(course);
      _ref1 = course.sectionRefs;
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        section = _ref1[_j];
        _results.push((function() {
          var _k, _len2, _ref2, _results1;
          _ref2 = section.days;
          _results1 = [];
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            day = _ref2[_k];
            _results1.push(this.courseCalendar[day].push(section));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Calendar.computeCss = function(start, end) {
      var height_pixels, start_pixels;
      start_pixels = (start - Calendar.options.start_hour) * Calendar.options.pixels_per_hour;
      height_pixels = Math.abs(end - start) * Calendar.options.pixels_per_hour;
      return {
        "top": start_pixels,
        "height": height_pixels
      };
    };

    Calendar.options = {
      pixels_per_hour: 42,
      start_hour: 8
    };

    Calendar.getValidSemesters = function() {
      var effectiveMonth, i, month, semester, semesters, year, _i;
      semesters = [];
      month = new Date().getMonth();
      year = new Date().getFullYear();
      effectiveMonth = month + 2;
      for (i = _i = 0; _i <= 2; i = ++_i) {
        if (effectiveMonth > 11) {
          effectiveMonth %= 12;
          year++;
        }
        semester = Math.floor(effectiveMonth / 4) + 1;
        effectiveMonth += 4;
        semesters.push(year + '' + semester);
      }
      semesters;

      return semesters = ['20133', '20141'];
    };

    Calendar.hours = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23];

    Calendar.days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

    return Calendar;

  })();
});
